### ISSUE TITLE
Errors in test files are silently ignored

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jorgenschaefer/emacs-buttercup#107]
If a test file throws an error, the error is ignored and any test suites that were defined before the error was thrown are run. Any test suites defined after the error are never defined or run, and buttercup erroneously reports a successful result even though some tests never ran. This problem masked some test failures is my expect-closures branch, as described here: https://github.com/jorgenschaefer/emacs-buttercup/pull/100#issuecomment-325148055.

**Comment by DarwinAwardWinner** [comment]
Looking at the code, I see that `buttercup-run-discover` is intentionally suppressing errors while loading test files. What is the rationale for this?

**Comment by jorgenschaefer** [comment]
Hm. I remember I added this for a reason, but I forgot what it was. If no tests fail without it, that's fine! :-D

**Comment by ebpa** [comment]
@jorgenschaefer Please reopen this issue.  The fix by @DarwinAwardWinner for this is a regression of #68.  Reporting the context (i.e. the file being loaded) is essential for locating a host of problems at runtime.  Relying on the error message exclusively is wholly inadequate.

I agree with @DarwinAwardWinner's observation of suppressed tests; the overall exit status should reflect whether all located test files were loaded successfully.  #68 should be amended with that in mind, but not removed.  At the very least it should be modified to re-signal the error with the additional context:

```
(condition-case err
    (load file nil t)
  (error
   (error (format "Error while loading %s:\n%s" file (error-message-string err)))))
```

In my opinion however, durability is desirable.  It is useful to run as many tests as possible and provide their summaries- with the caveat of course that not all test files were successfully loaded.

For example:

> Ran 100 out of 100 specs, 0 failed, in 1.2 seconds.
> Failed loading 1 file

With the appropriate non-zero exit status.

**Comment by DarwinAwardWinner** [comment]
Hmm. All the tests passed after I made that change, so I guess there is no test for #68. We should probably add one to make sure this doesn't happen again. 

The problem I see with catching and re-throwing the error with additional context is that if, I'm not mistaken, you lose the original error's backtrace. Perhaps an `unwind-protect` should be used instead, so that the original error is still raised? (e.g. see https://emacs.stackexchange.com/a/13792/2046)

**Comment by DarwinAwardWinner** [comment]
In the longer term, maybe the test suite struct should gain two more slots, one for the file name in which it was defined (something like `(or load-file-name buffer-file-name)`), and one for load error status, which should be non-nil if an error was encountered while defining the suite.

**Comment by ebpa** [comment]
@DarwinAwardWinner

> Hmm. All the tests passed after I made that change, so I guess there is no test for #68. We should probably add one to make sure this doesn't happen again.

Agreed.  I don't see any existing tests for `buttercup-run-discover`.  It might be a good idea to refactor it to make it more easily testable.  Perhaps extracting `(buttercup--parse-cli-args args) => parameter alist`, `(buttercup-test-files dirs patterns) => test file list`, `(buttercup-load-test-files files) => test suites`?

>The problem I see with catching and re-throwing the error with additional context is that if, I'm not mistaken, you lose the original error's backtrace.

That did occur to me when originally submitting #68 , but that function is/was not for programmatic use, so my thinking at the time was that nothing is effectively lost since buttercup doesn't report its own stack traces.  `unwind-protect` would be a better choice and could accommodate decidedly durable behavior.

I really like your suggestion for including filename in the suite/spec data structure.  It would be very useful in implementing an interactive reporter.  I don't think it is necessary for #68 or this issue though.

**Comment by jorgenschaefer** [comment]
Reopened as requested – I see the problem, and agree with your analysis and ideas. It should also be possible to run the loading of files in a similar environment as the tests themselves so buttercup can capture the backtrace itself, making it possible to ignore the error and also print the backtrace.

**Comment by alphapapa** [comment]
*Please* fix this.  I just spent an hour trying to figure out why I was getting `Symbol’s function definition is void` errors that were referring to functions that are not used in my project.  Buttercup was loading old, outdated elisp files with `test-` in their names, which I did not intend to be loaded when I run the Buttercup tests I am currently writing.

I was only able to find the problem by coming here, looking up the now-reverted diff, deleting the `.cask/../buttercup.elc` file, manually applying the diff to `.cask/../buttercup.el`, and re-running the tests.  Now I can see the problems easily:

```
Error while loading /home/me/src/emacs/org-ql/test-all-dates.el:
Symbol’s function definition is void: org-ql-agenda
Error while loading /home/me/src/emacs/org-ql/test-clocked.el:
Symbol’s function definition is void: org-ql
```

And now I know to remove those obsolete files.  But I could have easily spent more hours going in circles trying to figure out where those errors were coming from, since as far as I could tell, there was no *active* code in my project that could have caused them.

**Comment by wasamasa** [comment]
@alphapapa Would something like `(let ((debug-on-error t)) (load file nil t))` do the trick? That way the debugger would be popped up in the GUI and a backtrace printed at the console. The error message is otherwise too easy to overlook.

**Comment by snogge** [comment]
@wasamasa @alphapapa , please provide feedback on #216 to fix this. I'll leave the PR open a while to collect comments.
