### ISSUE TITLE
Multi-line `it` descriptions output all but last line then the whole description.

### ISSUE THREAD

**Issue by ekaschalk** [jorgenschaefer/emacs-buttercup#138]
All but the last line of a multi-line `it` description is repeated in the testing output:

```
(describe "foo"
  (it "bar
bar
baz"
    (expect t)))
```

```
foo
  bar
bar
  bar
bar
baz (0.07ms)
```

`describe` however is fine:

```
(describe "foo"
  (describe "bar
baz"
    (it "bee"
      (expect t))))
```

```
foo
  bar
baz
    bee (0.06ms)
```

I'm writing some tests referencing indentation on multi-line forms, so I thought to embed the form I'm testing into the testing output. I'll just move it into a `describe` block or something else, but thought to raise the issue. Thanks for this library, it has been very useful.

**Comment by snogge** [comment]
Does it work if you turn off colored output?  I think this is because the description of specs is first printed in the default color, then erased and reprinted in green for success, red for failure and so on. 
I realize this reply was a long time coming, so I'll probably try to reproduce myself eventually.

How would you like this to work? No color for multitlines? Just switch the color of the last line? Suggestions welcome.
