### ISSUE TITLE
Called times doesn't increase if error was thrown

### ISSUE THREAD

**Issue by rndusr** [jorgenschaefer/emacs-buttercup#139]
```elisp
(defun foo () "anything")
(describe "Called times increases"
          (it "when error was thrown"
              (spy-on 'foo :and-throw-error 'error)
              (expect (foo) :to-throw 'error)
              (expect 'foo :to-have-been-called-times 1)))
```
This test fails for me with buttercup 1.16.

**Comment by DarwinAwardWinner** [comment]
The reason for this is that buttercup records the result of each call to the function *after*, which obviously needs to include the return value. So if the function throws an error, the code that records the call is never run. This could be fixed with some creative use of `unwind-protect`, and at the same time the spy could be modified to record errors thrown by the function as well.

Relevant code: https://github.com/jorgenschaefer/emacs-buttercup/blob/master/buttercup.el#L1111-L1116

**Comment by DarwinAwardWinner** [comment]
Side note: I think `buttercup--spy-on-and-call-fake` and its argument `fake-function` may be misnomers now, since they are used for all spy functions, even ones that call through to the original.
