### ISSUE TITLE
Cannot load test file on Emacs 27

### ISSUE THREAD

**Issue by Alexander-Miller** [jorgenschaefer/emacs-buttercup#198]
When running the [treemacs build](https://github.com/Alexander-Miller/treemacs/blob/master/Makefile#L15) on Emacs 27 I am running into the strange error that my test file allegedly cannot be found, both locally and on travis:

![loaderror](https://user-images.githubusercontent.com/5951157/92028854-fc157a80-ed64-11ea-91ea-66ab41f1b313.png)

The file is clearly present and the build runs without issue, so this is either a treemacs or a buttercup problem.

My build is a fairly straightforward `cask exec buttercup` with the additional of loading code from some sub-directories, so I don't think that's to blame.

The build does go through if I call `expand-file-name` on the file being loaded, so the relative path seems to be the cause. I had simply assumed that this is just some new Emacs 27 change and had already prepared a PR, but buttercup's own tests have no such problem.

Any idea what is going on here?

**Comment by snogge** [comment]
I'm not sure why, but Emacs 27.1 requires a `-L . ` on the buttercup commandline. This use has been documented in several places, most recently in the [README.md](README.md) file in  commit 178c7954f8bb6e1209966f11c41587609048f258. This was added because of some feedback, but I cannot find any matching issue at this time.
