### ISSUE TITLE
Struggling to define matcher that calls a matcher

### ISSUE THREAD

**Issue by sellout** [jorgenschaefer/emacs-buttercup#248]
In https://github.com/sellout/elisp-reader.el/pull/2/commits/c462ec913ac94a3adf29e4d8a9f516ce383be5e4#diff-df405920574e0b4d13b951703b62761c4f725985e8f1e328e40a8f1ce923d476R39-R67 I define two matchers with the same goal. The first accepts a function to call (and works), the second accepts a matcher instead of a function (and doesn’t work).

The gist is that I want to call two functions on the argument to my matcher, and then compare the results of the two functions. If I compare them with a function directly, no problem. But if I instead try to pass the results to another matcher for comparison, it fails.

<details>
<summary>test output</summary>

```
Running 4 specs.
elisp-reader
  reading
    function matcher
      reads strings      reads strings (0.05ms)
      reads symbols      reads symbols (0.04ms)
    nested matcher
      reads strings      reads strings  FAILED (0.03ms)
      reads symbols      reads symbols  FAILED (0.03ms)
========================================
elisp-reader reading nested matcher reads strings
error: (cl-assertion-failed ((functionp fun) "Expected FUN to be a function" (oclosure-lambda (buttercup--thunk (expr '"xyz")) nil (buttercup--mark-stackframe) "xyz")))
========================================
elisp-reader reading nested matcher reads symbols
error: (cl-assertion-failed ((functionp fun) "Expected FUN to be a function" (oclosure-lambda (buttercup--thunk (expr 'foo)) nil (buttercup--mark-stackframe) foo)))
Ran 4 specs, 2 failed, in 4.06ms.
2 Buttercup tests failed
```
</details>

Now, I _know_ my code is wrong (e.g., I have a quoted oclosure, so of course it’s not a function), but the more I dig in, the more I feel like I’m getting it wrong much earlier and shouldn’t be pressing forward in this direction.

How should I be calling a nested matcher? The only example I see is `:not`, but that simply passes its arguments to the next matcher without any preprocessing. I don’t want to call `buttercup-expect` or friends, because I want to get the result back and do some post-processing, not just `buttercup-fail`.

Also, defining matchers seems to involve a bunch of internal (`buttercup--`) definitions. I feel like it’d be useful to have a separate `buttercup-matcher.el` that provides a bunch of those functions, and then when you’re _defining_ matchers, you `(require 'buttercup-matcher)`, and when you’re using them, you just `(require 'buttercup)`.

**Comment by sellout** [comment]
One comment on the code … `ert--process-results` just extracts the common bits from the two matcher definitions, to hopefully make it easier to compare the two implementations.

**Comment by snogge** [comment]
I don't think the nested matchers approach is the best way, unless you think you benefit greatly from their explanations.
For the simplest comparisons like `eq` and `equals`, buttercup uses the explainers from the `ert` library.  You could do that too in the first type of matcher if you like.
Another option is to add a macro to your packages tests that expand to the `expect` form you want.
Example:
```elisp
(er-expect-equal "\"xyz\"") 
->  (expect (er-read-from-string "\"xyz\"") :to-equal (funcall er-*orig-read-from-string* "\"xyz\""))
```
You could also eval `(funcall er-*orig-read-from-string* "\"xyz\"")` during macro expansion.  I think that would make the messages in mismatch cases better:
```
Expected `(er-read-from-string "\"xyz\"")' to equal `("xyz" . 3)', but instead it was `("xyz" . 2)'.
```

----
Some notes on the draft matchers:

The name `ert--process-results` confused me a bit.  I first thought it was related to the `ert` (Emacs Regression Test) framwork.  Then I realized it was an acronym for "elisp reader test".  You might want to use a different prefix as `ert-` is already taken.

The `buttercup--wrap-expr` function is really only meant as a implementation aid for the `expect` macro, fromwhich it was extracted.  When used outside that macro it will not return a function, but a list that can be eval-ed to a function.  Changing the `:read-results` matcher to
```elisp
(buttercup-define-matcher :read-results (string matcher &rest args)
  "Reads the provided STRING with both our reader and Emacs’ reader, comparing
the results with the provided MATCHER."
  (ert--process-results
   (funcall string)
   (lambda (our-result orig-result)
     (buttercup--apply-matcher (funcall matcher)
                               (append args
                                       (cl-loop for val in (list our-result orig-result)
                                                collect (eval (buttercup--wrap-expr val) t)))))))
```
makes one of the failing tests (the "xyz" one) work.  Not sure what is needed to pass the second (symbol) test, and whether the problem is in buttercup or in your code. 

I don't think anyone considered how to create the type of nested matchers you are trying to use.  While digging into your problem I considered a `buttercup-transform-thunk` function like this
```elisp
;; only for emacs with oclosure support
(defun buttercup-transform-thunk (fn thunk)
  "Return a new thunk that wraps FN around THUNK, but uses the same `expr` value as THUNK."
         (oclosure-lambda
             (buttercup--thunk
              (expr (buttercup--thunk--expr thunk))) ()
           (buttercup--mark-stackframe)
           (funcall fn (funcall thunk)))))
  )
```
which would let you call functions on the values and then pass them to a new matcher. It worked, but it was not immediately obvious where the values in the `:equal` explanation came from.  Where there used to be three variants - the original expression, the resulting value and the wanted value - there are now also two transformed values.

Requiring the use of internal functions to define matchers is obviously not ideal. I'll have to think about which parts should be made public functions and what should be private.  The documentation probably also needs an overhaul.  I don't think there is any point in splitting the matcher functions into a separate file, it would always have to be loaded from the main buttercup file in order to define the built-in matchers.

**Comment by sellout** [comment]
Thank you for the very detailed explanation and suggestions!

> I don't think the nested matchers approach is the best way, unless you think you benefit greatly from their explanations. For the simplest comparisons like `eq` and `equals`, buttercup uses the explainers from the `ert` library. You could do that too in the first type of matcher if you like.

You’re right – my hope was to take advantage of the existing explanations for other matchers, but it probably doesn’t help me too much, as the cases when, say, the result matches, but the index into the input stream differs can’t reasonably take advantage of the unexpected-success explanation. When I first put this together, I wasn’t considering that I also needed to handle the result messages differently, only that I needed to pre-process the input.

> The name `ert--process-results` confused me a bit. I first thought it was related to the `ert` (Emacs Regression Test) framwork. Then I realized it was an acronym for "elisp reader test". You might want to use a different prefix as `ert-` is already taken.

Yes, sorry, I realized this afterward. I only extracted that function for the purpose of this issue, so that name will go away anyway.

I definitely have to spend some time processing all this, but your response is very helpful. Thanks again.
