### ISSUE TITLE
before-each clause swallows errors

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#49]
Hi Jorgen,

Here's an example; this test fails, but the exception is not reported, causing one to think that there's an issue with the expect (whereas the issue is with the `before-each`.

```
(describe "buttercup"
  :var (x y)
  (before-each (setq x 0) (error "Badly written test") (setq y 1))
  (it "swallows errors in before-each"
    (expect x :to-equal y)))
```

It took me a while to understand why one of my tests was failing, because in fact the error was not in the test, but to an error being thrown in the before-each clause.

Let me know if I'm doing something wrong :) Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! You're doing everything right, this is a bug :-)

**Comment by jorgenschaefer** [comment]
Small correction, the lack of reporting is a side effect of #13 not being implemented, i.e. Buttercup can not currently recognize multiple errors. To implement this correctly, it would also need to record where the error happened (spec itself, before-each, after-each, etc.).

**Comment by DarwinAwardWinner** [comment]
I'm not sure when this changed, but as of b6deeff I get:

```
Running 1 specs.

buttercup
  swallows errors in before-each  FAILED

========================================
buttercup swallows errors in before-each

Traceback (most recent call last):
  (error "Badly written test")
  (signal error ("Badly written test"))
error: (error "Badly written test")


Ran 1 specs, 1 failed, in 0.0 seconds.
```

So I think this is fixed?

**Comment by snogge** [comment]
The behaviour changed in a1c7bff21fa6a3fca9f5dfe2cd2964ffa00924ab .
`buttercup--update-with-funcall` is used both for running `before-each` forms, the `it` form, and the `after-each` forms.  Before this commit, the return status of each such form was stored as the spec total state, meaning the last form won.  With this change, only `passed` state (assumed to be the initial state) is overwritten by new data.  
It could be argued that failures in `before-each` and `after-each` should be handled differently from actual failing testcases, but that is not what this issue is about.  I think this issue should be closed.  What do you think @jorgenschaefer, @cpitclaudel ?
